.

diff --git a/scripts/launch b/scripts/launch
--- a/scripts/launch
+++ b/scripts/launch
@@ -42,18 +42,18 @@ DOCKER_VERSION="$(docker --version | awk '{ print $3 }')"
 REGEX="([0-9]+)\.([0-9]+)\.([0-9]+),"
 
 # pin major version at 1, in case pfs needs update
-if [ $(echo "$DOCKER_VERSION" | sed -E "s/$REGEX/\1/") -ne "1" ]
-then
-    echo "This version of pfs only supports Docker 1.x, you're running $DOCKER_VERSION"
-    echo "Please upgrade pfs for support"
-    exit 1
-# docker versions below 1.5 are not supported
-elif [ $(echo "$DOCKER_VERSION" | sed -E "s/$REGEX/\2/") -lt "5" ]
-then
-    echo "Docker >= 1.5.0 is required"
-    echo "See: https://docs.docker.com/installation/ubuntulinux/#docker-maintained-package-installation"
-    exit 1
-fi
+# if [ $(echo "$DOCKER_VERSION" | sed -E "s/$REGEX/\1/") -ne "1" ]
+# then
+#     echo "This version of pfs only supports Docker 1.x, you're running $DOCKER_VERSION"
+#     echo "Please upgrade pfs for support"
+#     exit 1
+# # docker versions below 1.5 are not supported
+# elif [ $(echo "$DOCKER_VERSION" | sed -E "s/$REGEX/\2/") -lt "5" ]
+# then
+#     echo "Docker >= 1.5.0 is required"
+#     echo "See: https://docs.docker.com/installation/ubuntulinux/#docker-maintained-package-installation"
+#     exit 1
+# fi
 
 # btrfs --version | grep 3.14 || { echo 'Upgrade btrfs-tools to 3.14.' ; exit 1; }
 
